name: tourny-frontend
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: shovikghosh/tourny
  source_dir: frontend
  build_command: npm ci && npm run build
  run_command: npm start
  envs:
  - key: NEXT_PUBLIC_API_BASE_URL
    value: ${tourny-backend.URL}/api
  - key: NODE_ENV
    value: "production" 