name: tourny-frontend
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: your-github-username/tourny
  build_command: npm run build
  run_command: npm start
  envs:
  - key: API_BASE_URL
    value: https://tourny-backend-xxxxx.ondigitalocean.app/api
  - key: NODE_ENV
    value: production 