name: tourny-backend
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
      repo: shovikghosh/tourny
    # Optional: If your backend code is not in the root directory, add source_dir
    # source_dir: path/to/your/backend/code
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    # Add health checks if you have Spring Boot Actuator configured
    # health_check:
    #   http_path: /actuator/health
    envs:
      # Corrected database references
      - key: SPRING_DATASOURCE_URL
        value: ${db.DATABASE_URL}
      - key: SPRING_DATASOURCE_USERNAME
        value: ${db.USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${db.PASSWORD}
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: "org.postgresql.Driver"
      # Other env variables
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
    # Optional: Specify instance size and count
    # instance_size_slug: basic-xs
    # instance_count: 1
databases:
  - engine: PG
    name: tourny-db
    production: false # Set to true for production databases
    version: "14"